openapi: 3.1.0
info:
  title: Instagram Post Fetcher via FlashAPI
  version: 1.0.2
  description: Fetches recent Instagram posts by username using FlashAPI on RapidAPI.

servers:
  - url: https://flashapi1.p.rapidapi.com

paths:
  /ig/posts_username/:
    get:
      summary: Get recent Instagram posts by username
      operationId: getInstagramPosts
      parameters:
        - name: user
          in: query
          required: true
          description: Instagram username (without @)
          schema:
            type: string
        - name: nocors
          in: query
          required: false
          description: Set to false to get full CORS-compliant data
          schema:
            type: string  # Some APIs treat boolean as string, so use string to match ?nocors=false
        - name: x-rapidapi-host
          in: header
          required: true
          schema:
            type: string
            default: flashapi1.p.rapidapi.com
        - name: x-rapidapi-key
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved post data
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  result:
                    type: array
                    items:
                      type: object
        '401':
          description: Unauthorized – check API key
        '500':
          description: Server error

components:
  schemas: {}